# Generated by Django 5.2.7 on 2025-11-06 18:28

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_alter_project_options_alter_project_code_1c_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Integration nomi', max_length=255, unique=True)),
                ('wsdl_url', models.URLField(help_text='1C Web Service WSDL URL', max_length=500)),
                ('method_nomenklatura', models.CharField(default='GetProductList', help_text="Nomenklatura'larni olish uchun method nomi", max_length=255)),
                ('method_clients', models.CharField(default='GetClientList', help_text="Client'larni olish uchun method nomi", max_length=255)),
                ('chunk_size', models.IntegerField(default=100, help_text="Bir vaqtda qancha ma'lumot yuklash (chunk size)")),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Integration tavsifi', null=True)),
                ('project', models.ForeignKey(help_text="Qaysi project'ga tegishli", on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='api.project')),
            ],
            options={
                'verbose_name': 'Integration',
                'verbose_name_plural': 'Integrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('sync_type', models.CharField(choices=[('nomenklatura', 'Nomenklatura'), ('clients', 'Clients')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('fetching', 'Fetching'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], db_index=True, default='fetching', max_length=50)),
                ('total', models.IntegerField(default=0)),
                ('processed', models.IntegerField(default=0)),
                ('created', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('progress_percent', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integration.integration')),
            ],
            options={
                'verbose_name': 'Integration Log',
                'verbose_name_plural': 'Integration Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['project', 'is_deleted'], name='integration_project_793f4b_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['is_active', 'is_deleted'], name='integration_is_acti_d0ca32_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['integration', 'status'], name='integration_integra_efef15_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['task_id'], name='integration_task_id_8e0caf_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['sync_type', 'status'], name='integration_sync_ty_2d2ae6_idx'),
        ),
    ]
