# Generated by Django 5.2.7 on 2025-11-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_rename_integrationlog_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationlog',
            options={'ordering': ['-start_time'], 'verbose_name': 'Integration Log', 'verbose_name_plural': 'Integration Logs'},
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
