# Generated by Django 5.2.7 on 2026-01-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_alter_integrationlog_options_integrationlog_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='chunk_size',
            field=models.IntegerField(default=50, help_text="Bir vaqtda qancha ma'lumot yuklash (chunk size)"),
        ),
    ]
