# Generated by Django 5.2.7 on 2026-01-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_alter_integration_chunk_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='password',
            field=models.CharField(blank=True, help_text='SOAP Authentication Password', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='integration',
            name='username',
            field=models.CharField(blank=True, help_text='SOAP Authentication Username', max_length=255, null=True),
        ),
    ]
