# Generated by Django 5.2.7 on 2026-01-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_integration_password_integration_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationlog',
            name='item_errors',
            field=models.JSONField(blank=True, default=list, help_text='Alohida itemlar uchun xatoliklar'),
        ),
    ]
