# Generated by Django

from django.db import migrations, models
import django.core.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('visit_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_code', models.CharField(db_index=True, max_length=50)),
                ('agent_name', models.CharField(max_length=255)),
                ('agent_phone', models.CharField(blank=True, max_length=20)),
                ('client_code', models.CharField(db_index=True, max_length=100)),
                ('client_name', models.CharField(max_length=255)),
                ('client_address', models.TextField(blank=True)),
                ('visit_type', models.CharField(choices=[('PLANNED', 'Rejalashtirilgan'), ('UNPLANNED', 'Rejadan tashqari'), ('ADDITIONAL', "Qo'shimcha"), ('FOLLOW_UP', 'Takroriy tashrif'), ('EMERGENCY', 'Shoshilinch')], db_index=True, default='PLANNED', max_length=20)),
                ('visit_status', models.CharField(choices=[('SCHEDULED', 'Rejalashtirilgan'), ('CONFIRMED', 'Tasdiqlangan'), ('IN_PROGRESS', 'Jarayonda'), ('COMPLETED', 'Yakunlangan'), ('CANCELLED', 'Bekor qilingan'), ('POSTPONED', 'Kechiktirilgan'), ('NO_SHOW', 'Kelmaganlar')], db_index=True, default='SCHEDULED', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Past'), ('MEDIUM', "O'rta"), ('HIGH', 'Yuqori'), ('URGENT', 'Shoshilinch')], default='MEDIUM', max_length=10)),
                ('planned_date', models.DateField(db_index=True)),
                ('planned_time', models.TimeField(blank=True, null=True)),
                ('planned_duration_minutes', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)])),
                ('actual_start_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_in_address', models.TextField(blank=True)),
                ('check_in_accuracy', models.FloatField(blank=True, null=True)),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('purpose', models.TextField(blank=True)),
                ('tasks_planned', models.JSONField(blank=True, default=list)),
                ('tasks_completed', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('next_visit_notes', models.TextField(blank=True)),
                ('client_satisfaction', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('agent_notes', models.TextField(blank=True)),
                ('supervisor_notes', models.TextField(blank=True)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('cancelled_by', models.CharField(blank=True, max_length=100)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
                'db_table': 'visits',
                'ordering': ['-planned_date', '-planned_time'],
            },
        ),
        migrations.CreateModel(
            name='VisitPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('plan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_code', models.CharField(db_index=True, max_length=50)),
                ('client_code', models.CharField(db_index=True, max_length=100)),
                ('frequency', models.CharField(choices=[('DAILY', 'Har kuni'), ('WEEKLY', 'Haftalik'), ('BIWEEKLY', 'Ikki haftada bir'), ('MONTHLY', 'Oylik'), ('QUARTERLY', 'Choraklik')], default='WEEKLY', max_length=20)),
                ('planned_weekday', models.IntegerField(blank=True, help_text='0=Monday, 6=Sunday', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('planned_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.CharField(choices=[('LOW', 'Past'), ('MEDIUM', "O'rta"), ('HIGH', 'Yuqori'), ('URGENT', 'Shoshilinch')], default='MEDIUM', max_length=10)),
                ('auto_generate', models.BooleanField(default=True)),
                ('generate_days_ahead', models.IntegerField(default=7)),
            ],
            options={
                'db_table': 'visit_plans',
                'ordering': ['agent_code', 'planned_weekday', 'planned_time'],
                'unique_together': {('agent_code', 'client_code', 'planned_weekday', 'planned_time')},
            },
        ),
        migrations.CreateModel(
            name='VisitImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_type', models.CharField(choices=[('PRODUCT', 'Mahsulot'), ('SHELF', 'Javon'), ('STOREFRONT', "Do'kon ko'rinishi"), ('RECEIPT', 'Kvitansiya'), ('SIGNATURE', 'Imzo'), ('OTHER', 'Boshqa')], default='PRODUCT', max_length=50)),
                ('image_url', models.URLField(max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('client_image_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='visits.visit')),
            ],
            options={
                'db_table': 'visit_images',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['agent_code', 'planned_date', 'visit_status'], name='visits_agent_c_e34c93_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['client_code', 'actual_start_time'], name='visits_client__22e2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['visit_type', 'created_at'], name='visits_visit_t_e81a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['visit_status', 'planned_date'], name='visits_visit_s_9f8fd4_idx'),
        ),
        migrations.AddIndex(
            model_name='visitplan',
            index=models.Index(fields=['agent_code', 'is_active'], name='visit_plans_agent_c_4b3c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='visitplan',
            index=models.Index(fields=['client_code', 'is_active'], name='visit_plans_client__9e5a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='visitimage',
            index=models.Index(fields=['visit', 'image_type'], name='visit_image_visit_i_7c4d1b_idx'),
        ),
    ]
