# Generated by Django 5.2.7 on 2026-01-14 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='visit',
            new_name='visits_agent_c_4b326e_idx',
            old_name='visits_agent_c_e34c93_idx',
        ),
        migrations.RenameIndex(
            model_name='visit',
            new_name='visits_client__ec0688_idx',
            old_name='visits_client__22e2cf_idx',
        ),
        migrations.RenameIndex(
            model_name='visit',
            new_name='visits_visit_t_2c3464_idx',
            old_name='visits_visit_t_e81a5d_idx',
        ),
        migrations.RenameIndex(
            model_name='visit',
            new_name='visits_visit_s_cbc6d0_idx',
            old_name='visits_visit_s_9f8fd4_idx',
        ),
        migrations.RenameIndex(
            model_name='visitimage',
            new_name='visit_image_visit_i_4b2fa2_idx',
            old_name='visit_image_visit_i_7c4d1b_idx',
        ),
        migrations.RenameIndex(
            model_name='visitplan',
            new_name='visit_plans_agent_c_f5157b_idx',
            old_name='visit_plans_agent_c_4b3c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='visitplan',
            new_name='visit_plans_client__2da520_idx',
            old_name='visit_plans_client__9e5a2f_idx',
        ),
    ]
