# Generated by Django 5.2.7 on 2026-01-19 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_authproject_wsdl_url_alt_alter_authproject_wsdl_url'),
        ('visits', '0002_rename_visits_agent_c_e34c93_idx_visits_agent_c_4b326e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='visit',
            name='visits_agent_c_4b326e_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitplan',
            name='visit_plans_agent_c_f5157b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='visitplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='visit',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='users.authproject'),
        ),
        migrations.AddField(
            model_name='visit',
            name='sync_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='sync_status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('SYNCED', 'Sinxronlangan'), ('FAILED', 'Xatolik')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='visitplan',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_plans', to='users.authproject'),
        ),
        migrations.AlterUniqueTogether(
            name='visitplan',
            unique_together={('project', 'agent_code', 'client_code', 'planned_weekday', 'planned_time')},
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['project', 'agent_code', 'planned_date', 'visit_status'], name='visits_project_b0a87e_idx'),
        ),
        migrations.AddIndex(
            model_name='visitplan',
            index=models.Index(fields=['project', 'agent_code', 'is_active'], name='visit_plans_project_649dc1_idx'),
        ),
    ]
