# Generated by Django 5.2.7 on 2026-01-19 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_remove_client_client_clie_city_446b1c_idx_and_more'),
        ('users', '0003_userprofile_project'),
        ('visits', '0003_remove_visit_visits_agent_c_4b326e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='visit',
            name='visits_client__ec0688_idx',
        ),
        migrations.RemoveIndex(
            model_name='visit',
            name='visits_project_b0a87e_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitplan',
            name='visit_plans_client__2da520_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitplan',
            name='visit_plans_project_649dc1_idx',
        ),
        migrations.AddField(
            model_name='visit',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Tashrifni amalga oshiradigan agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='visit',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Tashrif buyuriladigan mijoz', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='client.client'),
        ),
        migrations.AddField(
            model_name='visitplan',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_plans', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='visitplan',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_plans', to='client.client'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['project', 'agent', 'planned_date', 'visit_status'], name='visits_project_ff578a_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['client', 'actual_start_time'], name='visits_client__86a557_idx'),
        ),
        migrations.AddIndex(
            model_name='visitplan',
            index=models.Index(fields=['project', 'agent', 'is_active'], name='visit_plans_project_b3c79d_idx'),
        ),
        migrations.AddIndex(
            model_name='visitplan',
            index=models.Index(fields=['client', 'is_active'], name='visit_plans_client__cfe0b5_idx'),
        ),
    ]
