# Generated by Django 5.2.7 on 2026-01-19 16:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_remove_client_client_clie_city_446b1c_idx_and_more'),
        ('references', '0001_initial'),
        ('users', '0003_userprofile_project'),
        ('visits', '0004_remove_visit_visits_client__ec0688_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitStepResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.FloatField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(default=False)),
                ('value_photo', models.ImageField(blank=True, null=True, upload_to='visit_steps/')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['step__sort_order'],
            },
        ),
        migrations.RemoveIndex(
            model_name='visit',
            name='visits_visit_s_cbc6d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='visit',
            name='visits_project_ff578a_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitimage',
            name='visit_image_visit_i_4b2fa2_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitplan',
            name='visit_plans_project_b3c79d_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitplan',
            name='visit_plans_client__cfe0b5_idx',
        ),
        migrations.RenameIndex(
            model_name='visit',
            new_name='visits_visit_t_42c2af_idx',
            old_name='visits_visit_t_2c3464_idx',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='cancelled_reason',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='next_visit_notes',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='tasks_completed',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='tasks_planned',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='visit_status',
        ),
        migrations.AddField(
            model_name='visit',
            name='duration',
            field=models.DurationField(blank=True, help_text='Aniq davomiylik (calculated)', null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.ForeignKey(blank=True, help_text='Tashrif holati (Dynamic)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='references.visitstatus'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='priority',
            field=models.ForeignKey(blank=True, help_text='Prioritet (Dynamic)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='references.visitpriority'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_type',
            field=models.ForeignKey(blank=True, help_text='Tashrif turi (Dynamic)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='references.visittype'),
        ),
        migrations.AlterField(
            model_name='visitimage',
            name='client_image_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='visitplan',
            name='planned_weekday',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='visitplan',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.visitpriority'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['project', 'agent', 'planned_date', 'status'], name='visits_project_a0aa6e_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['status', 'planned_date'], name='visits_status__5e1792_idx'),
        ),
        migrations.AddField(
            model_name='visitstepresult',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='references.visitstep'),
        ),
        migrations.AddField(
            model_name='visitstepresult',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_results', to='visits.visit'),
        ),
        migrations.AlterUniqueTogether(
            name='visitstepresult',
            unique_together={('visit', 'step')},
        ),
    ]
