# Generated by Django 5.2.7 on 2026-01-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_visitstepresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visit',
            name='cancelled_reason',
            field=models.TextField(blank=True),
        ),
    ]
