# Generated by Django 5.2.7 on 2026-01-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0006_visit_cancelled_at_visit_cancelled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='next_visit_notes',
            field=models.TextField(blank=True, help_text='Notes for the next scheduled visit'),
        ),
        migrations.AddField(
            model_name='visit',
            name='tasks_completed',
            field=models.JSONField(blank=True, default=list, help_text='List of tasks completed during this visit'),
        ),
        migrations.AddField(
            model_name='visit',
            name='tasks_planned',
            field=models.JSONField(blank=True, default=list, help_text='List of tasks planned for this visit'),
        ),
    ]
