# Generated by Django 5.2.7 on 2026-01-10 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Project nomi (masalan: Evyap)', max_length=255)),
                ('project_code', models.CharField(db_index=True, help_text='Unikal project kodi (clientdan keladi)', max_length=100, unique=True)),
                ('wsdl_url', models.URLField(help_text='1C WSDL URL manzili')),
                ('service_url', models.URLField(blank=True, help_text='Service URL (agar WSDL dan farq qilsa)', null=True)),
            ],
            options={
                'verbose_name': 'Auth Project',
                'verbose_name_plural': 'Auth Projects',
                'db_table': 'auth_project',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_1c', models.CharField(blank=True, db_index=True, help_text='1C dagi user kodi', max_length=100, null=True)),
                ('code_project', models.CharField(blank=True, help_text='1C CodeProject', max_length=100, null=True)),
                ('code_sklad', models.CharField(blank=True, help_text='1C CodeSklad', max_length=100, null=True)),
                ('type_1c', models.CharField(blank=True, help_text='1C Type', max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profile',
            },
        ),
    ]
