# Generated by Django 5.2.7 on 2026-01-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authproject',
            name='wsdl_url_alt',
            field=models.URLField(blank=True, help_text='Muqobil (alternative) 1C WSDL URL manzili', null=True),
        ),
        migrations.AlterField(
            model_name='authproject',
            name='wsdl_url',
            field=models.URLField(help_text='Asosiy 1C WSDL URL manzili'),
        ),
    ]
