# Generated by Django 5.2.7 on 2026-01-19 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_authproject_wsdl_url_alt_alter_authproject_wsdl_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='users.authproject'),
        ),
    ]
