# Generated by Django 5.2.7 on 2026-01-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_region_code',
            field=models.CharField(blank=True, db_index=True, help_text='Business Region Code (1C)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_region_name',
            field=models.CharField(blank=True, help_text='Business Region Name (1C)', max_length=255, null=True),
        ),
    ]
