# Generated by Django 5.2.7 on 2026-01-28 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_business_region_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentBusinessRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_regions', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Agent Business Region',
                'verbose_name_plural': 'Agent Business Regions',
                'db_table': 'agent_business_region',
                'unique_together': {('profile', 'code')},
            },
        ),
    ]
