# Generated by Django 5.2.7 on 2025-11-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_clientimage_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_code_1c',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clientimage',
            name='is_main',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_deleted', 'is_active'], name='client_clie_is_dele_ce57ce_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_code_1c', 'is_deleted'], name='client_clie_client__cfe770_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name', 'is_deleted'], name='client_clie_name_f561b9_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email', 'is_deleted'], name='client_clie_email_29a555_idx'),
        ),
        migrations.AddIndex(
            model_name='clientimage',
            index=models.Index(fields=['client', 'is_deleted'], name='client_clie_client__f3bf08_idx'),
        ),
        migrations.AddIndex(
            model_name='clientimage',
            index=models.Index(fields=['is_main', 'is_deleted'], name='client_clie_is_main_4cf825_idx'),
        ),
    ]
