# Generated by Django 5.2.7 on 2025-11-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_clientimage_source_clientimage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='actual_address',
            field=models.TextField(blank=True, help_text='Haqiqiy manzil', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='additional_phones',
            field=models.JSONField(blank=True, default=list, help_text="Qo'shimcha telefon raqamlari (JSON)", null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='annual_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Yillik daromad', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='business_type',
            field=models.CharField(blank=True, help_text='Biznes turi', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, help_text='Shahar', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, help_text='Kompaniya nomi', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Kontakt email', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Kontakt shaxs', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Kontakt telefon', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_position',
            field=models.CharField(blank=True, help_text='Lavozim', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, default='Uzbekistan', help_text='Davlat', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kredit limiti', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='currency',
            field=models.CharField(blank=True, default='UZS', help_text='Valyuta', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='employee_count',
            field=models.IntegerField(blank=True, help_text='Xodimlar soni', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='established_date',
            field=models.DateField(blank=True, help_text='Tashkil etilgan sana', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='fax',
            field=models.CharField(blank=True, help_text='Faks raqami', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='industry',
            field=models.CharField(blank=True, help_text='Soha/Industriya', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_address',
            field=models.TextField(blank=True, help_text='Yuridik manzil', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text="Qo'shimcha meta ma'lumotlar (JSON)", null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, help_text="Qo'shimcha izohlar", null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_terms',
            field=models.CharField(blank=True, help_text="To'lov shartlari", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Pochta indeksi', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='priority',
            field=models.IntegerField(blank=True, default=0, help_text='Prioritet (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reyting (0-5)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='region',
            field=models.CharField(blank=True, help_text='Viloyat/Hudud', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='registration_number',
            field=models.CharField(blank=True, help_text="Ro'yxatdan o'tish raqami", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='social_media',
            field=models.JSONField(blank=True, default=dict, help_text='Ijtimoiy tarmoqlar (JSON)', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='source',
            field=models.CharField(blank=True, help_text='Manba', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Teglar (JSON)', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_id',
            field=models.CharField(blank=True, help_text='INN/STIR', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, help_text='Veb-sayt', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['city', 'region'], name='client_clie_city_446b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['industry', 'business_type'], name='client_clie_industr_b4006b_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['rating', 'priority'], name='client_clie_rating_0e5254_idx'),
        ),
    ]
