# Generated by Django 5.2.7 on 2026-01-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_agentlocation_accelerometer_x_and_more'),
        ('client', '0006_client_actual_address_client_additional_phones_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clientimage',
            index=models.Index(fields=['created_at', 'is_deleted'], name='client_clie_created_cf545a_idx'),
        ),
    ]
