# Generated by Django 5.2.7 on 2026-01-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_agentlocation_accelerometer_x_and_more'),
        ('client', '0007_clientimage_client_clie_created_cf545a_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='clients', to='api.project'),
        ),
    ]
