# Generated by Django 5.2.7 on 2026-01-10 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_agentlocation_accelerometer_x_and_more'),
        ('client', '0008_client_projects'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='client_clie_client__cfe770_idx',
        ),
        migrations.AddField(
            model_name='client',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Proyekt', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='api.project'),
        ),
        migrations.AlterField(
            model_name='client',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='clients_old', to='api.project'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('project', 'client_code_1c')},
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['project', 'client_code_1c', 'is_deleted'], name='client_clie_project_15e514_idx'),
        ),
    ]
