# Generated by Django 5.2.7 on 2026-01-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_remove_client_client_clie_client__cfe770_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='projects',
        ),
    ]
