# Generated by Django 5.2.7 on 2026-01-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_agentlocation_accelerometer_x_and_more'),
        ('client', '0010_remove_client_projects'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='client_clie_city_446b1c_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_clie_industr_b4006b_idx',
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['city', 'is_deleted'], name='client_clie_city_fec391_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['region', 'is_deleted'], name='client_clie_region_2eebe8_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_at', 'is_deleted'], name='client_clie_created_2bafc5_idx'),
        ),
    ]
