# Generated by Django 5.2.7 on 2026-01-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text='Config key (e.g. GEMINI_API_KEY)', max_length=255, unique=True)),
                ('value', models.TextField(help_text='Config value')),
                ('description', models.CharField(blank=True, help_text='Key description', max_length=500, null=True)),
                ('is_secret', models.BooleanField(default=True, help_text='If true, value is sensitive (API key, etc.)')),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['key'],
            },
        ),
    ]
