# Generated by Django 5.2.7 on 2026-01-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=100)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('purpose', models.CharField(blank=True, help_text='e.g. Nomenklatura Description', max_length=255, null=True)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'AI Token Usage',
                'verbose_name_plural': 'AI Token Usage Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('secret', 'Secret Key'), ('select', 'Selection'), ('number', 'Number')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='options',
            field=models.JSONField(blank=True, help_text="Possible values for 'select' type", null=True),
        ),
    ]
