# Generated by Django 5.2.7 on 2026-01-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aitokenusage_systemsettings_field_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Human-readable name', max_length=100)),
                ('model_id', models.CharField(help_text='API identifier (e.g. models/gemini-1.5-pro)', max_length=255, unique=True)),
                ('provider', models.CharField(choices=[('google', 'Google (Gemini)'), ('openai', 'OpenAI (GPT)'), ('anthropic', 'Anthropic (Claude)'), ('custom', 'Custom Provider')], default='google', max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('meta_data', models.JSONField(blank=True, default=dict, help_text='Additional params (temperature, etc.)')),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('secret', 'Secret Key'), ('select', 'Selection'), ('multiselect', 'Multi-Selection'), ('number', 'Number')], default='text', max_length=20),
        ),
    ]
