# Generated by Django 5.2.7 on 2026-01-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aimodel_alter_systemsettings_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='provider',
            field=models.CharField(choices=[('google', 'Google (Gemini)'), ('puter', 'Puter.com (Free)'), ('openai', 'OpenAI (GPT)'), ('anthropic', 'Anthropic (Claude)'), ('custom', 'Custom Provider')], default='google', max_length=50),
        ),
    ]
