# Generated by Django 5.2.7 on 2025-11-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='project',
            name='code_1c',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='is_main',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_deleted', 'is_active'], name='api_project_is_dele_717d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['code_1c', 'is_deleted'], name='api_project_code_1c_8c3173_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name', 'is_deleted'], name='api_project_name_444f34_idx'),
        ),
        migrations.AddIndex(
            model_name='projectimage',
            index=models.Index(fields=['project', 'is_deleted'], name='api_project_project_6fcb1b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectimage',
            index=models.Index(fields=['is_main', 'is_deleted'], name='api_project_is_main_2162f4_idx'),
        ),
    ]
