# Generated by Django 5.2.7 on 2025-11-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_project_options_alter_project_code_1c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Rasm toifasi yoki teg', max_length=120),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='note',
            field=models.CharField(blank=True, default='', help_text="Rasm haqida qo'shimcha izoh", max_length=255),
        ),
    ]
