# Generated by Django 5.2.7 on 2025-11-21 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_projectimage_category_projectimage_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploader_name', models.CharField(help_text="Yuboruvchi ismi (masalan: 'Agent: John Doe', 'Client: ABC Company')", max_length=100)),
                ('uploader_type', models.CharField(choices=[('agent', 'Agent'), ('client', 'Client'), ('admin', 'Administrator'), ('system', 'System'), ('other', 'Other')], default='other', help_text='Yuboruvchi turi', max_length=50)),
                ('uploader_contact', models.CharField(blank=True, help_text="Yuboruvchi kontakt ma'lumotlari (telefon, email, va hokazo)", max_length=255, null=True)),
                ('upload_location', models.CharField(blank=True, help_text="Rasm yuklangan joy (masalan: 'Toshkent, Chilonzor', 'Mobile App', 'Web Admin')", max_length=255, null=True)),
                ('upload_device', models.CharField(blank=True, help_text="Qurilma ma'lumotlari (masalan: 'iPhone 12', 'Samsung Galaxy', 'Web Browser')", max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text="Qo'shimcha izohlar", null=True)),
            ],
            options={
                'verbose_name': 'Image Source',
                'verbose_name_plural': 'Image Sources',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['uploader_type', 'is_deleted'], name='api_imageso_uploade_b79cd5_idx'), models.Index(fields=['is_active', 'is_deleted'], name='api_imageso_is_acti_e16e19_idx')],
            },
        ),
        migrations.AddField(
            model_name='projectimage',
            name='source',
            field=models.ForeignKey(blank=True, help_text="Rasmni yuboruvchi ma'lumotlari", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_images', to='api.imagesource'),
        ),
        migrations.CreateModel(
            name='ImageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text="Status kodi (masalan: 'store_before', 'store_after', 'product_main')", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Status nomi (masalan: 'Magazin - Tashrif oldidan', 'Magazin - Tashrifdan keyin')", max_length=100)),
                ('description', models.TextField(blank=True, help_text="Status haqida batafsil ma'lumot", null=True)),
                ('icon', models.CharField(blank=True, default='', help_text="Icon nomi yoki emoji (masalan: 'store', 'product', 'info')", max_length=50)),
                ('order', models.IntegerField(default=0, help_text="Tartib raqami (admin panelda ko'rinish tartibi)")),
            ],
            options={
                'verbose_name': 'Image Status',
                'verbose_name_plural': 'Image Statuses',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['code', 'is_deleted'], name='api_imagest_code_7581a7_idx'), models.Index(fields=['is_active', 'is_deleted'], name='api_imagest_is_acti_95c4c3_idx')],
            },
        ),
        migrations.AddField(
            model_name='projectimage',
            name='status',
            field=models.ForeignKey(blank=True, help_text='Rasm statusi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_images', to='api.imagestatus'),
        ),
    ]
