# Generated by Django 5.2.7 on 2025-11-21 16:03

from django.db import migrations


def create_default_image_statuses(apps, schema_editor):
    """Default image statuslarni yaratish"""
    ImageStatus = apps.get_model('api', 'ImageStatus')
    
    default_statuses = [
        {
            'code': 'store_before',
            'name': 'Magazin - Tashrif oldidan',
            'description': 'Agent tashrif buyurishdan oldin magazin holati',
            'icon': 'store',
            'order': 1,
            'is_active': True,
            'is_deleted': False,
        },
        {
            'code': 'store_after',
            'name': 'Magazin - Tashrifdan keyin',
            'description': 'Agent tashrif buyurganidan keyin magazin holati',
            'icon': 'store',
            'order': 2,
            'is_active': True,
            'is_deleted': False,
        },
        {
            'code': 'store_info',
            'name': 'Magazin - Umumiy ma\'lumot',
            'description': 'Magazin haqidagi oddiy information rasmlar',
            'icon': 'info',
            'order': 3,
            'is_active': True,
            'is_deleted': False,
        },
        {
            'code': 'product_main',
            'name': 'Mahsulot - Asosiy rasm',
            'description': 'Mahsulotning asosiy ko\'rinish rasmi',
            'icon': 'product',
            'order': 4,
            'is_active': True,
            'is_deleted': False,
        },
        {
            'code': 'product_gallery',
            'name': 'Mahsulot - Galereya',
            'description': 'Mahsulot galereyasi rasmlari',
            'icon': 'gallery',
            'order': 5,
            'is_active': True,
            'is_deleted': False,
        },
        {
            'code': 'product_packaging',
            'name': 'Mahsulot - Qadoqlash',
            'description': 'Mahsulot qadoqlash rasmlari',
            'icon': 'package',
            'order': 6,
            'is_active': True,
            'is_deleted': False,
        },
        {
            'code': 'other',
            'name': 'Boshqa',
            'description': 'Boshqa turdagi rasmlar',
            'icon': 'other',
            'order': 99,
            'is_active': True,
            'is_deleted': False,
        },
    ]
    
    for status_data in default_statuses:
        ImageStatus.objects.get_or_create(
            code=status_data['code'],
            defaults=status_data
        )


def reverse_create_default_image_statuses(apps, schema_editor):
    """Reverse migration - default statuslarni o'chirish"""
    ImageStatus = apps.get_model('api', 'ImageStatus')
    ImageStatus.objects.filter(
        code__in=['store_before', 'store_after', 'store_info', 'product_main', 
                  'product_gallery', 'product_packaging', 'other']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_imagesource_projectimage_source_imagestatus_and_more'),
    ]

    operations = [
        migrations.RunPython(
            create_default_image_statuses,
            reverse_create_default_image_statuses
        ),
    ]
