# Generated by Django 5.2.7 on 2025-11-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_create_default_image_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_code', models.CharField(db_index=True, help_text='Agentni identifikatsiya qilish uchun code (unikal emas, lekin tez-tez ishlatiladi)', max_length=100)),
                ('agent_name', models.CharField(blank=True, default='', help_text="Agent to'liq ismi", max_length=150)),
                ('agent_phone', models.CharField(blank=True, default='', help_text='Aloqa telefoni', max_length=50)),
                ('region', models.CharField(blank=True, default='', help_text='Hudud yoki filial nomi', max_length=120)),
                ('device_id', models.CharField(blank=True, default='', help_text='Qurilma ID (IMEI yoki UUID)', max_length=120)),
                ('device_name', models.CharField(blank=True, default='', help_text='Qurilma nomi/modeli', max_length=120)),
                ('platform', models.CharField(blank=True, default='', help_text='Operatsion tizim (Android/iOS)', max_length=50)),
                ('app_version', models.CharField(blank=True, default='', help_text='Mobil ilova versiyasi', max_length=40)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude (WGS84)', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude (WGS84)', max_digits=9)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, help_text='Aniqlik (metr)', max_digits=7, null=True)),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, help_text='Balandlik (m)', max_digits=8, null=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, help_text='Tezlik (m/s)', max_digits=6, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, help_text="Yo'nalish (gradus)", max_digits=6, null=True)),
                ('battery_level', models.DecimalField(blank=True, decimal_places=1, help_text='Batareya (%)', max_digits=4, null=True)),
                ('is_charging', models.BooleanField(default=False)),
                ('signal_strength', models.CharField(blank=True, default='', help_text='Signal kuchi yoki operator', max_length=50)),
                ('logged_at', models.DateTimeField(blank=True, help_text="Agent qurilmasida yozilgan vaqt (agar mavjud bo'lsa)", null=True)),
                ('address', models.CharField(blank=True, default='', help_text='Geo reverse address', max_length=255)),
                ('note', models.TextField(blank=True, default='', help_text="Qo'shimcha izoh")),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Qo'shimcha meta ma'lumotlar (JSON)", null=True)),
            ],
            options={
                'verbose_name': 'Agent Location',
                'verbose_name_plural': 'Agent Locations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent_code', 'created_at'], name='api_agentlo_agent_c_a331a1_idx'), models.Index(fields=['is_deleted', 'is_active'], name='api_agentlo_is_dele_102811_idx')],
            },
        ),
    ]
