# Generated by Django 5.2.7 on 2025-11-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_agentlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentlocation',
            name='accelerometer_x',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Accelerometer X (m/s²)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='accelerometer_y',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Accelerometer Y (m/s²)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='accelerometer_z',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Accelerometer Z (m/s²)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='app_build_number',
            field=models.CharField(blank=True, default='', help_text='Build raqami', max_length=50),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='app_installation_date',
            field=models.DateTimeField(blank=True, help_text="Ilova o'rnatilgan sana", null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='app_last_update',
            field=models.DateTimeField(blank=True, help_text='Ilova oxirgi yangilangan sana', null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='battery_health',
            field=models.CharField(blank=True, default='', help_text='Batareya holati (Good, Fair, Poor, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='battery_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Batareya harorati (°C)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='battery_voltage',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Batareya kuchlanishi (V)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='camera_back',
            field=models.BooleanField(default=False, help_text='Orqa kamera mavjudligi'),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='camera_front',
            field=models.BooleanField(default=False, help_text='Old kamera mavjudligi'),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='camera_resolution',
            field=models.CharField(blank=True, default='', help_text="Kamera o'lchami (masalan: 12MP)", max_length=50),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='cellular_network_type',
            field=models.CharField(blank=True, default='', help_text='Mobil tarmoq turi (GSM, CDMA, LTE, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='cellular_operator',
            field=models.CharField(blank=True, default='', help_text='Mobil operator nomi', max_length=100),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='city',
            field=models.CharField(blank=True, default='', help_text='Shahar nomi', max_length=100),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='connection_type',
            field=models.CharField(blank=True, default='', help_text='Ulanish turi (WiFi, Mobile, Ethernet, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='country',
            field=models.CharField(blank=True, default='', help_text='Davlat nomi', max_length=100),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='device_fingerprint',
            field=models.CharField(blank=True, default='', help_text='Qurilma fingerprint (hash)', max_length=255),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='device_manufacturer',
            field=models.CharField(blank=True, default='', help_text='Ishlab chiqaruvchi (Samsung, Apple, Xiaomi, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='device_model',
            field=models.CharField(blank=True, default='', help_text='Qurilma modeli (SM-G991B, iPhone 13, etc.)', max_length=100),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='encryption_enabled',
            field=models.BooleanField(default=False, help_text='Shifrlash yoqilganmi'),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='gyroscope_x',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Gyroscope X (rad/s)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='gyroscope_y',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Gyroscope Y (rad/s)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='gyroscope_z',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Gyroscope Z (rad/s)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='humidity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Namlik (%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP manzil', null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='is_jailbroken',
            field=models.BooleanField(default=False, help_text='Qurilma jailbreak qilinganmi (iOS)'),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='is_rooted',
            field=models.BooleanField(default=False, help_text='Qurilma root qilinganmi'),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='light_sensor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Yorug'lik sensori (lux)", max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='location_provider',
            field=models.CharField(blank=True, default='', help_text='Lokatsiya manbasi (GPS, Network, Passive)', max_length=50),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='magnetometer_x',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Magnetometer X (μT)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='magnetometer_y',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Magnetometer Y (μT)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='magnetometer_z',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Magnetometer Z (μT)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='network_type',
            field=models.CharField(blank=True, default='', help_text='Tarmoq turi (WiFi, 4G, 5G, LTE, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='os_version',
            field=models.CharField(blank=True, default='', help_text='OS versiyasi (Android 12, iOS 15.0, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='postal_code',
            field=models.CharField(blank=True, default='', help_text='Pochta indeksi', max_length=20),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='pressure',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Bosim (hPa)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='proximity_sensor',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Proximity sensor (cm)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='ram_available',
            field=models.BigIntegerField(blank=True, help_text='Mavjud RAM (byte)', null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='ram_total',
            field=models.BigIntegerField(blank=True, help_text='Jami RAM (byte)', null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='screen_density',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ekran zichligi (DPI)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='screen_height',
            field=models.IntegerField(blank=True, help_text='Ekran balandligi (pixel)', null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='screen_lock_type',
            field=models.CharField(blank=True, default='', help_text='Ekran qulfi turi (None, PIN, Pattern, Fingerprint, Face, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='screen_width',
            field=models.IntegerField(blank=True, help_text='Ekran kengligi (pixel)', null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='storage_available',
            field=models.BigIntegerField(blank=True, help_text='Mavjud xotira (byte)', null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='storage_total',
            field=models.BigIntegerField(blank=True, help_text='Jami xotira (byte)', null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Harorat (°C)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text='Vaqt mintaqasi (UTC+5, Asia/Tashkent, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='wifi_bssid',
            field=models.CharField(blank=True, default='', help_text='WiFi BSSID (MAC address)', max_length=50),
        ),
        migrations.AddField(
            model_name='agentlocation',
            name='wifi_ssid',
            field=models.CharField(blank=True, default='', help_text='WiFi tarmoq nomi (SSID)', max_length=100),
        ),
    ]
