# Generated by Django 5.2.7 on 2026-01-10 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('welcome_message', models.TextField(default="Xizmat ko'rsatish markazimizga xush kelibsiz! Sizga qanday yordam bera olamiz?")),
                ('is_chat_enabled', models.BooleanField(default=True)),
                ('auto_reply_enabled', models.BooleanField(default=False)),
                ('auto_reply_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chat Sozlamasi',
                'verbose_name_plural': 'Chat Sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('closed', 'Yopilgan'), ('pending', 'Kutilmoqda')], default='open', max_length=20)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('responder', models.ForeignKey(blank=True, help_text='Admin yoki Supervayzer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats_as_responder', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Mijoz (Client)', on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suhbat',
                'verbose_name_plural': 'Suhbatlar',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('is_read', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['created_at'],
            },
        ),
    ]
