# Generated by Django 5.2.7 on 2025-11-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenklatura', '0002_alter_nomenklaturaimage_nomenklatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenklatura',
            name='code_1c',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='nomenklatura',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='nomenklaturaimage',
            name='is_main',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='nomenklatura',
            index=models.Index(fields=['is_deleted', 'is_active'], name='nomenklatur_is_dele_5c97ce_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenklatura',
            index=models.Index(fields=['code_1c', 'is_deleted'], name='nomenklatur_code_1c_910491_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenklatura',
            index=models.Index(fields=['name', 'is_deleted'], name='nomenklatur_name_860167_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenklaturaimage',
            index=models.Index(fields=['nomenklatura', 'is_deleted'], name='nomenklatur_nomenkl_cb7106_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenklaturaimage',
            index=models.Index(fields=['is_main', 'is_deleted'], name='nomenklatur_is_main_9330a1_idx'),
        ),
    ]
