# Generated by Django 5.2.7 on 2025-11-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenklatura', '0003_alter_nomenklatura_code_1c_alter_nomenklatura_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenklaturaimage',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Rasm toifasi yoki teg', max_length=120),
        ),
        migrations.AddField(
            model_name='nomenklaturaimage',
            name='note',
            field=models.CharField(blank=True, default='', help_text="Rasm haqida qo'shimcha izoh", max_length=255),
        ),
    ]
