# Generated by Django 5.2.7 on 2025-11-21 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_imagesource_projectimage_source_imagestatus_and_more'),
        ('nomenklatura', '0004_nomenklaturaimage_category_nomenklaturaimage_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenklaturaimage',
            name='source',
            field=models.ForeignKey(blank=True, help_text="Rasmni yuboruvchi ma'lumotlari", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomenklatura_images', to='api.imagesource'),
        ),
        migrations.AddField(
            model_name='nomenklaturaimage',
            name='status',
            field=models.ForeignKey(blank=True, help_text='Rasm statusi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomenklatura_images', to='api.imagestatus'),
        ),
    ]
