# Generated by Django 5.2.7 on 2025-11-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenklatura', '0005_nomenklaturaimage_source_nomenklaturaimage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenklatura',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Barkod', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Asosiy narx', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='brand',
            field=models.CharField(blank=True, help_text='Brend', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='category',
            field=models.CharField(blank=True, db_index=True, help_text='Kategoriya', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='color',
            field=models.CharField(blank=True, help_text='Rang', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Narx (xarajat)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='currency',
            field=models.CharField(blank=True, default='UZS', help_text='Valyuta', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='dimensions',
            field=models.CharField(blank=True, help_text="O'lchamlari (LxWxH)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Chegirma foizi', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Yaroqlilik muddati', null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Ishlab chiqaruvchi', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='material',
            field=models.CharField(blank=True, help_text='Material', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='max_stock',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maksimal ombor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text="Qo'shimcha meta ma'lumotlar (JSON)", null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='min_stock',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimal ombor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='model',
            field=models.CharField(blank=True, help_text='Model', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='notes',
            field=models.TextField(blank=True, help_text="Qo'shimcha izohlar", null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='popularity_score',
            field=models.IntegerField(blank=True, default=0, help_text='Mashhurligi (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='production_date',
            field=models.DateField(blank=True, help_text='Ishlab chiqarilgan sana', null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reyting (0-5)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sotuv narxi', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text="SEO kalit so'zlar", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='series',
            field=models.CharField(blank=True, help_text='Seriya', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='size',
            field=models.CharField(blank=True, help_text="O'lcham", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='SKU (Stock Keeping Unit)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='source',
            field=models.CharField(blank=True, help_text='Manba', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='stock_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ombor miqdori', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='subcategory',
            field=models.CharField(blank=True, help_text='Quyi kategoriya', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Teglar (JSON)', null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='QQS foizi', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='unit_of_measure',
            field=models.CharField(blank=True, help_text="O'lchov birligi", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='vendor_code',
            field=models.CharField(blank=True, help_text='Sotuvchi kodi', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Hajm (m³)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='warranty_period',
            field=models.IntegerField(blank=True, help_text='Kafolat muddati (oy)', null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Og'irlik (kg)", max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='nomenklatura',
            index=models.Index(fields=['sku', 'barcode'], name='nomenklatur_sku_ee1204_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenklatura',
            index=models.Index(fields=['category', 'subcategory'], name='nomenklatur_categor_fdf22b_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenklatura',
            index=models.Index(fields=['brand', 'manufacturer'], name='nomenklatur_brand_81ecfe_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenklatura',
            index=models.Index(fields=['rating', 'popularity_score'], name='nomenklatur_rating_bfd450_idx'),
        ),
    ]
