# Generated by Django 5.2.7 on 2026-01-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_agentlocation_accelerometer_x_and_more'),
        ('nomenklatura', '0006_nomenklatura_barcode_nomenklatura_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenklatura',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='nomenclatures', to='api.project'),
        ),
    ]
