# Generated by Django 5.2.7 on 2026-01-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_agentlocation_accelerometer_x_and_more'),
        ('nomenklatura', '0007_nomenklatura_projects'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nomenklaturaimage',
            index=models.Index(fields=['created_at', 'is_deleted'], name='nomenklatur_created_9ba247_idx'),
        ),
    ]
