# Generated by Django 5.2.7 on 2026-01-10 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_agentlocation_accelerometer_x_and_more'),
        ('nomenklatura', '0008_nomenklaturaimage_nomenklatur_created_9ba247_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nomenklatura',
            name='nomenklatur_code_1c_910491_idx',
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Proyekt', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nomenclatures', to='api.project'),
        ),
        migrations.AlterField(
            model_name='nomenklatura',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='nomenclatures_old', to='api.project'),
        ),
        migrations.AlterUniqueTogether(
            name='nomenklatura',
            unique_together={('project', 'code_1c')},
        ),
        migrations.AddIndex(
            model_name='nomenklatura',
            index=models.Index(fields=['project', 'code_1c', 'is_deleted'], name='nomenklatur_project_a8ccee_idx'),
        ),
    ]
