# Generated by Django 5.2.7 on 2026-01-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomenklatura', '0009_remove_nomenklatura_nomenklatur_code_1c_910491_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomenklatura',
            name='projects',
        ),
    ]
