# Generated by Django 5.2.7 on 2026-01-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenklatura', '0010_remove_nomenklatura_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenklatura',
            name='article_code',
            field=models.CharField(blank=True, db_index=True, help_text='Artikul kodi', max_length=100, null=True),
        ),
    ]
