# Generated by Django 5.2.7 on 2026-01-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenklatura', '0011_nomenklatura_article_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenklatura',
            name='country',
            field=models.CharField(blank=True, help_text='Ishlab chiqarilgan davlat', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='country_code',
            field=models.CharField(blank=True, help_text='Davlat kodi', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='roditel',
            field=models.CharField(blank=True, help_text='Roditel (1C)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='supplier',
            field=models.CharField(blank=True, help_text='Yetkazib beruvchi', max_length=255, null=True),
        ),
    ]
