# Generated by Django 5.2.7 on 2026-01-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_agentlocation_accelerometer_x_and_more'),
        ('nomenklatura', '0012_nomenklatura_country_nomenklatura_country_code_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nomenklatura',
            name='nomenklatur_categor_fdf22b_idx',
        ),
        migrations.RemoveIndex(
            model_name='nomenklatura',
            name='nomenklatur_brand_81ecfe_idx',
        ),
        migrations.AddIndex(
            model_name='nomenklatura',
            index=models.Index(fields=['category', 'is_deleted'], name='nomenklatur_categor_bf9000_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenklatura',
            index=models.Index(fields=['brand', 'is_deleted'], name='nomenklatur_brand_25d015_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenklatura',
            index=models.Index(fields=['base_price', 'is_deleted'], name='nomenklatur_base_pr_5f0233_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenklatura',
            index=models.Index(fields=['created_at', 'is_deleted'], name='nomenklatur_created_fde6b8_idx'),
        ),
    ]
