# Generated by Django 5.2.7 on 2026-01-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenklatura', '0013_remove_nomenklatura_nomenklatur_categor_fdf22b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenklatura',
            name='enrichment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='AI enrichment status', max_length=20),
        ),
        migrations.AddField(
            model_name='nomenklatura',
            name='last_enriched_at',
            field=models.DateTimeField(blank=True, help_text='Last successful enrichment time', null=True),
        ),
    ]
