# Generated by Django 5.2.7 on 2026-01-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomenklatura', '0014_nomenklatura_enrichment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenklaturaimage',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text="AI orqali qo'shilgan rasm"),
        ),
    ]
