"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-h$&jhhj!%)h$ccokz4)0zsmxl069tm*-vb%37trdzb=0t3-grk')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

DEFAULT_ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '0.0.0.0',
    '178.218.200.120',
    '192.168.0.101',
    '192.168.0.110',
    '192.168.0.111',
    '192.168.0.129',
]
ALLOWED_HOSTS = [
    host.strip() for host in os.environ.get('ALLOWED_HOSTS', '').split(',')
    if host.strip()
] or DEFAULT_ALLOWED_HOSTS

DEFAULT_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://178.218.200.120:1596',
    'http://192.168.0.101',
    'http://192.168.0.110',
    'http://192.168.0.111',
    'http://192.168.0.129',
    'http://192.168.0.129:8000',
    'http://178.218.200.120:1596',
    'http://178.218.200.120'
]
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
] or DEFAULT_TRUSTED_ORIGINS


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'django_filters',
    'corsheaders',
    'ckeditor',
    'ckeditor_uploader',
    'imagekit',
    
    # Caching and background tasks
    # 'cacheops',  # Optional - uncomment if installed
    # 'django_q',  # Commented - incompatible with Django 5.2.7, using threading instead

    'client',
    'nomenklatura',
    'api',
    'integration',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 60,  # Increased timeout for sync operations
            'check_same_thread': False,  # Allow multiple threads
        },
        'CONN_MAX_AGE': 600,  # Connection pooling
    }
}

# SQLite WAL mode - improves concurrency and prevents "readonly database" errors
# This is set via database connection initialization
from django.db.backends.signals import connection_created
from django.dispatch import receiver

@receiver(connection_created)
def setup_sqlite_wal_mode(sender, connection, **kwargs):
    """Enable WAL mode for SQLite to improve concurrency"""
    if connection.vendor == 'sqlite':
        with connection.cursor() as cursor:
            cursor.execute("PRAGMA journal_mode=WAL;")
            cursor.execute("PRAGMA synchronous=NORMAL;")  # Faster than FULL, still safe
            cursor.execute("PRAGMA cache_size=-64000;")  # 64MB cache
            cursor.execute("PRAGMA temp_store=MEMORY;")  # Use memory for temp tables


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = []
STATIC_APP_DIR = BASE_DIR / 'static'
if STATIC_APP_DIR.exists():
    STATICFILES_DIRS.append(STATIC_APP_DIR)

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_MAX_AGE = 60 * 60 * 24 * 30  # 30 days

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


CKEDITOR_UPLOAD_PATH = 'uploads/ckeditor/'

# ============================================================================
# CACHING CONFIGURATION - High Performance for 10K+ requests/minute
# ============================================================================

# Redis cache backend - much faster than database cache
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            'IGNORE_EXCEPTIONS': True,  # Don't break if Redis is down
            # 'PARSER_CLASS': 'redis.connection.HiredisParser',  # Faster parser (optional, requires hiredis)
        },
        'KEY_PREFIX': 'ecatalog',
        'TIMEOUT': 300,  # 5 minutes default
        'VERSION': 1,
    }
}

# Cacheops - automatic ORM query caching (optional)
# Uncomment if django-cacheops is installed
# CACHEOPS_REDIS = {
#     'host': os.environ.get('REDIS_HOST', '127.0.0.1'),
#     'port': int(os.environ.get('REDIS_PORT', 6379)),
#     'db': int(os.environ.get('REDIS_DB', 2)),
#     'socket_timeout': 3,
#     'ignore_exceptions': True,
# }
# 
# CACHEOPS = {
#     # Cache all queries for 5 minutes
#     'api.*': {'ops': 'all', 'timeout': 300},
#     'client.*': {'ops': 'all', 'timeout': 300},
#     'nomenklatura.*': {'ops': 'all', 'timeout': 300},
#     'integration.*': {'ops': 'get', 'timeout': 600},
#     'api.imagestatus': {'ops': 'all', 'timeout': 3600},
#     'api.imagesource': {'ops': 'all', 'timeout': 3600},
#     'api.agentlocation': {'ops': 'get', 'timeout': 60},
# }

# Session backend - using database for reliability
# If Redis is unavailable, cache-based sessions fail
# Using database-backed sessions ensures sessions work even without Redis
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_CACHE_ALIAS = 'default'

# ============================================================================
# BACKGROUND TASKS - Using threading (django-q2 incompatible with Django 5.2)
# ============================================================================
# Background tasks are handled via threading.Thread in integration/views.py
# For production, consider using Celery or django-rq
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'PAGE_SIZE_QUERY_PARAM': 'page_size',
    'MAX_PAGE_SIZE': 100,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
    },
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'E-Catalog API',
    'DESCRIPTION': '''
# E-Catalog Microservice API Documentation

Bu API Project, Nomenklatura va Client ma'lumotlarini boshqarish uchun yaratilgan Django REST Framework asosidagi microservice.

## Asosiy Xususiyatlar

- **Project Management** — Project'lar va ularning rasmlarini boshqarish
- **Nomenklatura Management** — Nomenklatura'lar va ularning rasmlarini boshqarish
- **Client Management** — Client'lar va ularning rasmlarini boshqarish (Authentication talab qilinadi)
- **Agent Locations** — Mobil agentlar tomonidan yuborilgan geolokatsiya va qurilma ma'lumotlari
- **Image Management** — Image Status va Image Source boshqaruvi
- **1C Integration** — 1C dan ma'lumotlarni yuklab olish
- **Excel Import/Export** — Project, Nomenklatura va Client'lar uchun Excel formatida import/export
- **Image Processing** — Rasmlarni turli o'lchamlarda (sm, md, lg, thumbnail) saqlash
- **JWT Authentication** — Token-based authentication
- **Pagination** — Sahifalash bilan ma'lumotlarni olish
- **Search & Filtering** — Qidirish va filtrlash imkoniyatlari

## Authentication

1. `POST /api/token/` — `username` va `password` yuboring. Javobda `access` va `refresh` token olasiz.
2. `Authorization: Bearer <access_token>` header'ini barcha himoyalangan endpointlarda yuboring.
3. `POST /api/token/refresh/` — `refresh` token yuborib yangi `access` token oling.
4. `POST /api/token/verify/` — mavjud tokenning yaroqliligini tekshiring.

> Test uchun: `http POST http://localhost:8000/api/token/ username=admin password=secret`

## Projects

### Project CRUD Operatsiyalari

- **GET /api/v1/project/** — Project'lar ro'yxatini olish
  
  **Filterlar:**
  - `search` — `code_1c`, `name`, `title` bo'yicha qidirish
  - `code_1c` — Aniq code bo'yicha filter
  - `name` — Aniq nom bo'yicha filter
  - `description_status` — `with` (description bor) | `without` (description yo'q)
  - `image_status` — `with` (rasm bor) | `without` (rasm yo'q)
  - `created_from` — Yaratilgan sanadan boshlab (YYYY-MM-DD)
  - `created_to` — Yaratilgan sana chegarasi (YYYY-MM-DD)
  - `updated_from` — Yangilangan sanadan boshlab (YYYY-MM-DD)
  - `updated_to` — Yangilangan sana chegarasi (YYYY-MM-DD)
  - `page` — Sahifa raqami (default: 1)
  - `page_size` — Sahifadagi elementlar soni (default: 20, max: 100)

- **GET /api/v1/project/{code_1c}/** — Bitta project ma'lumotini olish
- **POST /api/v1/project/** — Yangi project yaratish (`code_1c`, `name`, `title`, `description`, `is_active`)
- **PUT /api/v1/project/{code_1c}/** — Project'ni to'liq yangilash
- **PATCH /api/v1/project/{code_1c}/** — Project'ni qisman yangilash
- **DELETE /api/v1/project/{code_1c}/** — Project'ni soft-delete qilish

### Project Excel Operatsiyalari

- **GET /api/v1/project/export-xlsx/** — Project'larni Excel formatda eksport qilish (Authentication talab qilinadi)
- **GET /api/v1/project/template-xlsx/** — Excel shablon faylini yuklab olish (Authentication talab qilinadi)
- **POST /api/v1/project/import-xlsx/** — Excel fayldan Project'larni import qilish (Authentication talab qilinadi)

### Project Rasmlari

- **GET /api/v1/project-images/** — Project rasmlari ro'yxatini olish
  
  **Filterlar:**
  - `project` — Project ID bo'yicha filter
  - `is_main` — Asosiy rasm bo'yicha filter (true/false)
  - `category` — Rasm toifasi bo'yicha filter
  - `created_from` — Yaratilgan sanadan boshlab (YYYY-MM-DD)
  - `created_to` — Yaratilgan sana chegarasi (YYYY-MM-DD)

- **POST /api/v1/project-images/** — Bitta rasm yuklash (multipart/form-data)
- **POST /api/v1/project-images/bulk-upload/** — Bir nechta rasm yuklash
  - `project` — Project code_1c qiymati
  - `images[]` — Bir yoki bir nechta rasm fayli
  - `category` (optional) — Barcha rasmlar uchun umumiy toifa
  - `note` (optional) — Barcha rasmlar uchun umumiy izoh

## Clients

> **Diqqat:** Barcha client endpointlari JWT authentication talab qiladi.

### Client CRUD Operatsiyalari

- **GET /api/v1/client/** — Client'lar ro'yxatini olish (Authentication talab qilinadi)
  
  **Filterlar:**
  - `search` — `client_code_1c`, `name`, `email` bo'yicha qidirish
  - `client_code_1c` — Aniq code bo'yicha filter
  - `name` — Aniq nom bo'yicha filter
  - `email` — Email bo'yicha filter
  - `description_status` — `with` (description bor) | `without` (description yo'q)
  - `image_status` — `with` (rasm bor) | `without` (rasm yo'q)
  - `created_from` — Yaratilgan sanadan boshlab (YYYY-MM-DD)
  - `created_to` — Yaratilgan sana chegarasi (YYYY-MM-DD)
  - `updated_from` — Yangilangan sanadan boshlab (YYYY-MM-DD)
  - `updated_to` — Yangilangan sana chegarasi (YYYY-MM-DD)
  - `page` — Sahifa raqami (default: 1)
  - `page_size` — Sahifadagi elementlar soni (default: 20, max: 100)

- **GET /api/v1/client/{client_code_1c}/** — Bitta client ma'lumotini olish (Authentication talab qilinadi)
- **POST /api/v1/client/** — Yangi client yaratish (Authentication talab qilinadi)
- **PUT /api/v1/client/{client_code_1c}/** — Client'ni to'liq yangilash (Authentication talab qilinadi)
- **PATCH /api/v1/client/{client_code_1c}/** — Client'ni qisman yangilash (Authentication talab qilinadi)
  > **Eslatma:** `client_code_1c` o'zgartirilmaydi
- **DELETE /api/v1/client/{client_code_1c}/** — Client'ni soft-delete qilish (Authentication talab qilinadi)

### Client Excel Operatsiyalari

- **GET /api/v1/client/export-xlsx/** — Client'larni Excel formatda eksport qilish (Authentication talab qilinadi)
- **GET /api/v1/client/template-xlsx/** — Excel shablon faylini yuklab olish (Authentication talab qilinadi)
- **POST /api/v1/client/import-xlsx/** — Excel fayldan Client'larni import qilish (Authentication talab qilinadi)

### Client Rasmlari

- **GET /api/v1/client-images/** — Client rasmlari ro'yxatini olish (Authentication talab qilinadi)
  
  **Filterlar:**
  - `client` — Client ID (database ID) bo'yicha filter (Integer)
  - `client_code_1c` — Client 1C kodi bo'yicha filter (String)
  - `is_main` — Asosiy rasm bo'yicha filter (true/false)
  - `category` — Rasm toifasi bo'yicha filter
  - `created_from` — Yaratilgan sanadan boshlab (YYYY-MM-DD)
  - `created_to` — Yaratilgan sana chegarasi (YYYY-MM-DD)

- **POST /api/v1/client-images/** — Bitta rasm yuklash (multipart/form-data) (Authentication talab qilinadi)
- **POST /api/v1/client-images/bulk-upload/** — Bir nechta rasm yuklash (Authentication talab qilinadi)
  - `client` — Client client_code_1c qiymati
  - `images[]` — Bir yoki bir nechta rasm fayli
  - `category` (optional) — Barcha rasmlar uchun umumiy toifa
  - `note` (optional) — Barcha rasmlar uchun umumiy izoh

## Nomenklatura

### Nomenklatura CRUD Operatsiyalari

- **GET /api/v1/nomenklatura/** — Nomenklatura'lar ro'yxatini olish
  
  **Filterlar:**
  - `search` — `code_1c`, `name` bo'yicha qidirish
  - `code_1c` — Aniq code bo'yicha filter
  - `name` — Aniq nom bo'yicha filter
  - `description_status` — `with` (description bor) | `without` (description yo'q)
  - `image_status` — `with` (rasm bor) | `without` (rasm yo'q)
  - `created_from` — Yaratilgan sanadan boshlab (YYYY-MM-DD)
  - `created_to` — Yaratilgan sana chegarasi (YYYY-MM-DD)
  - `updated_from` — Yangilangan sanadan boshlab (YYYY-MM-DD)
  - `updated_to` — Yangilangan sana chegarasi (YYYY-MM-DD)
  - `page` — Sahifa raqami (default: 1)
  - `page_size` — Sahifadagi elementlar soni (default: 20, max: 100)

- **GET /api/v1/nomenklatura/{code_1c}/** — Bitta nomenklatura ma'lumotini olish
- **POST /api/v1/nomenklatura/** — Yangi nomenklatura yaratish
- **PUT /api/v1/nomenklatura/{code_1c}/** — Nomenklatura'ni to'liq yangilash
- **PATCH /api/v1/nomenklatura/{code_1c}/** — Nomenklatura'ni qisman yangilash
- **DELETE /api/v1/nomenklatura/{code_1c}/** — Nomenklatura'ni soft-delete qilish

### Nomenklatura Excel Operatsiyalari

- **GET /api/v1/nomenklatura/export-xlsx/** — Nomenklatura'larni Excel formatda eksport qilish (Authentication talab qilinadi)
- **GET /api/v1/nomenklatura/template-xlsx/** — Excel shablon faylini yuklab olish (Authentication talab qilinadi)
- **POST /api/v1/nomenklatura/import-xlsx/** — Excel fayldan Nomenklatura'larni import qilish (Authentication talab qilinadi)

### Nomenklatura Rasmlari

- **GET /api/v1/nomenklatura-images/** — Nomenklatura rasmlari ro'yxatini olish
  
  **Filterlar:**
  - `nomenklatura` — Nomenklatura ID bo'yicha filter
  - `is_main` — Asosiy rasm bo'yicha filter (true/false)
  - `category` — Rasm toifasi bo'yicha filter
  - `created_from` — Yaratilgan sanadan boshlab (YYYY-MM-DD)
  - `created_to` — Yaratilgan sana chegarasi (YYYY-MM-DD)

- **POST /api/v1/nomenklatura-images/** — Bitta rasm yuklash (multipart/form-data)
- **POST /api/v1/nomenklatura-images/bulk-upload/** — Bir nechta rasm yuklash
  - `nomenklatura` — Nomenklatura code_1c qiymati
  - `images[]` — Bir yoki bir nechta rasm fayli
  - `category` (optional) — Barcha rasmlar uchun umumiy toifa
  - `note` (optional) — Barcha rasmlar uchun umumiy izoh

## Agent Locations

Mobil agentlar tomonidan yuborilgan geolokatsiya yozuvlari. Qurilma, lokatsiya, tarmoq, sensor va boshqa ma'lumotlar bilan birga saqlanadi.

> **Diqqat:** Barcha agent location endpointlari JWT authentication talab qiladi (GET so'rovlari uchun).

- **GET /api/v1/agent-locations/** — Agent lokatsiya yozuvlari ro'yxati (Authentication talab qilinadi)
  
  **Filterlar:**
  - `agent_code` — Agent kodi bo'yicha filter
  - `region` — Hudud bo'yicha filter
  - `platform` — Platforma (Android/iOS) bo'yicha filter
  - `device_id` — Qurilma ID bo'yicha filter
  - `date_from` — Yaratilgan sanadan boshlab (DateTime)
  - `date_to` — Yaratilgan sana chegarasi (DateTime)
  - `page` — Sahifa raqami
  - `page_size` — Sahifadagi elementlar soni

- **POST /api/v1/agent-locations/** — Yangi lokatsiya yozuvini yaratish
- **GET /api/v1/agent-locations/{id}/** — Bitta yozuvni olish (Authentication talab qilinadi)
- **PUT /api/v1/agent-locations/{id}/** — Yozuvni to'liq yangilash (Authentication talab qilinadi)
- **PATCH /api/v1/agent-locations/{id}/** — Yozuvni qisman yangilash (Authentication talab qilinadi)
- **DELETE /api/v1/agent-locations/{id}/** — Soft-delete qilish (Authentication talab qilinadi)

### AgentLocation Maydonlari

**Majburiy maydonlar:**
- `agent_code` (string) — Agent kodi
- `latitude` (decimal) — Latitude (WGS84)
- `longitude` (decimal) — Longitude (WGS84)

**Agent ma'lumotlari:**
- `agent_name`, `agent_phone`, `region`

**Qurilma ma'lumotlari:**
- `device_id`, `device_name`, `device_manufacturer`, `device_model`
- `platform`, `os_version`, `screen_width`, `screen_height`, `screen_density`
- `ram_total`, `ram_available`, `storage_total`, `storage_available`
- `camera_front`, `camera_back`, `camera_resolution`

**App ma'lumotlari:**
- `app_version`, `app_build_number`, `app_installation_date`, `app_last_update`

**Lokatsiya ma'lumotlari:**
- `accuracy`, `altitude`, `speed`, `heading`
- `city`, `country`, `postal_code`, `timezone`, `location_provider`, `address`

**Batareya ma'lumotlari:**
- `battery_level`, `is_charging`, `battery_health`, `battery_temperature`, `battery_voltage`

**Tarmoq ma'lumotlari:**
- `signal_strength`, `network_type`, `wifi_ssid`, `wifi_bssid`
- `cellular_operator`, `cellular_network_type`, `ip_address`, `connection_type`

**Sensor ma'lumotlari:**
- `accelerometer_x/y/z`, `gyroscope_x/y/z`, `magnetometer_x/y/z`
- `proximity_sensor`, `light_sensor`

**Atrof-muhit ma'lumotlari:**
- `temperature`, `humidity`, `pressure`

**Xavfsizlik ma'lumotlari:**
- `device_fingerprint`, `is_rooted`, `is_jailbroken`, `encryption_enabled`, `screen_lock_type`

**Qo'shimcha:**
- `logged_at`, `note`, `metadata` (JSON)

## Image Status va Image Source

### Image Status

Rasm statuslari — rasmning qaysi maqsadda ishlatilishini belgilaydi.

- **GET /api/v1/image-statuses/** — Image Status ro'yxati
- **POST /api/v1/image-statuses/** — Yangi status yaratish (Authentication talab qilinadi)
- **GET /api/v1/image-statuses/{id}/** — Bitta statusni olish
- **PUT/PATCH /api/v1/image-statuses/{id}/** — Statusni yangilash (Authentication talab qilinadi)
- **DELETE /api/v1/image-statuses/{id}/** — Statusni soft-delete qilish (Authentication talab qilinadi)

**Maydonlar:**
- `code` — Status kodi (masalan: 'store_before', 'store_after')
- `name` — Status nomi
- `description` — Tavsif
- `icon` — Icon nomi
- `order` — Ko'rinish tartibi

### Image Source

Rasmni yuboruvchi haqida ma'lumotlar.

- **GET /api/v1/image-sources/** — Image Source ro'yxati
- **POST /api/v1/image-sources/** — Yangi source yaratish (Authentication talab qilinadi)
- **GET /api/v1/image-sources/{id}/** — Bitta source'ni olish
- **PUT/PATCH /api/v1/image-sources/{id}/** — Source'ni yangilash (Authentication talab qilinadi)
- **DELETE /api/v1/image-sources/{id}/** — Source'ni soft-delete qilish (Authentication talab qilinadi)

**Maydonlar:**
- `uploader_name` — Yuboruvchi ismi
- `uploader_type` — Yuboruvchi turi (agent, client, admin, system, other)
- `uploader_contact` — Kontakt ma'lumotlari
- `upload_location` — Yuklangan joy
- `upload_device` — Qurilma
- `notes` — Qo'shimcha izohlar

## Integration (1C Sinxronizatsiya)

> **Diqqat:** Barcha integration endpointlari JWT authentication talab qilinadi.

- **GET /api/v1/integration/** — Integration sozlamalari ro'yxati (Authentication talab qilinadi)
- **POST /api/v1/integration/{id}/sync-nomenklatura/** — 1C dan nomenklatura'larni fon rejimida yuklash (Authentication talab qilinadi)
- **POST /api/v1/integration/{id}/sync-clients/** — 1C dan client'larni yuklash (Authentication talab qilinadi)
- **GET /api/v1/integration/sync-status/{task_id}/** — Fon jarayonining progressini kuzatish

**Sync javobida `task_id` qaytadi. Uni ishlatib status endpointiga murojaat qiling:**

**Statuslar:**
- `fetching` — 1C dan ma'lumotlar olinmoqda
- `processing` — Ma'lumotlar bazaga yozilmoqda
- `completed` — Jarayon muvaffaqiyatli yakunlandi
- `error` — Xatolik yuz berdi

### Integration Sozlamalari

`IntegrationSerializer` maydonlari:

| Field | Type | Description |
|-------|------|-------------|
| `name` | string | Integration nomi (unikal) |
| `project` | integer | Project ID (ForeignKey) |
| `wsdl_url` | string (URL) | 1C web-service WSDL manzili |
| `method_nomenklatura` | string | 1C dagi nomenklaturani qaytaruvchi method nomi |
| `method_clients` | string | 1C dagi clientlarni qaytaruvchi method nomi |
| `chunk_size` | integer | Bir qo'ng'iroqda qayta ishlanadigan elementlar soni |
| `description` | rich text | Integration haqida qo'shimcha ma'lumot |

### 1C → E-Catalog Ma'lumot Mapping

#### Nomenklatura Item

- `Code` → `code_1c`
- `Name` → `name`
- `Title` → `title`
- `Description` → `description`
- `Project` → Project nomi
- `Images` → Rasm URL'lari (`Image`, `ImageSm`, `ImageMd`, `ImageLg`, `IsMain`)

#### Client Item

- `Code` → `client_code_1c`
- `Name` → `name`
- `Email` → `email`
- `Phone` → `phone`
- `Description` → `description`
- `Images` → Rasm URL'lari

## Image Formats

Har bir rasm 4 xil o'lchamda saqlanadi:

- **image_url** — Original rasm
- **image_sm_url** — Kichik (300x300px) — mobil qurilmalar uchun
- **image_md_url** — O'rta (600x600px) — planshetlar uchun
- **image_lg_url** — Katta (1200x1200px) — desktop qurilmalar uchun
- **image_thumbnail_url** — Thumbnail (150x150px) — ro'yxatlar uchun

Barcha rasmlar JPEG formatida automatic ravishda generate qilinadi.

## Pagination

Barcha ro'yxat endpointlari pagination qiladi:

- `page` — Sahifa raqami (default: 1)
- `page_size` — Sahifadagi elementlar soni (default: 20, max: 100)

**Response formati:**
```json
{
  "count": 100,
  "next": "http://localhost:8000/api/v1/project/?page=2",
  "previous": null,
  "results": [...]
}
```

## Search & Filtering

### Search

`search` parametri — Barcha `search_fields` maydonlarida qidirish.

**Misol:**
- `/api/v1/client/?search=ABC` — `client_code_1c`, `name`, `email` da 'ABC' qidiruvchi

### Ordering

`ordering` parametri — Tartiblash.

**Misol:**
- `/api/v1/project/?ordering=name` — Nom bo'yicha A-Z tartiblash
- `/api/v1/project/?ordering=-created_at` — Yaratilgan sanasi bo'yicha teskari tartiblash

## Status Management

Barcha modellar `is_active` va `is_deleted` field'lariga ega:

- Soft delete: `PATCH /api/v1/{endpoint}/{id}/` — `{"is_deleted": true}`
- Active/Inactive: `PATCH /api/v1/{endpoint}/{id}/` — `{"is_active": false}`

## Qo'shimcha Ma'lumotlar

- **Swagger UI**: http://localhost:8000/api/docs/
- **ReDoc**: http://localhost:8000/api/redoc/
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/v1/',
    'TAGS': [
        {
            'name': 'Authentication',
            'description': 'JWT token olish, yangilash va tekshirish endpointlari. Access tokenni `Authorization: Bearer` header ida yuboring.',
        },
        {
            'name': 'Projects',
            'description': 'Project CRUD operatsiyalari va rasm boshqaruvi (list, search, create, update, delete, bulk image upload).',
        },
        {
            'name': 'Clients',
            'description': 'Client CRUD operatsiyalari, faqat autentifikatsiya qilingan foydalanuvchilar uchun. Rasm boshqaruvi va bulk upload misollari.',
        },
        {
            'name': 'Nomenklatura',
            'description': 'Nomenklatura CRUD operatsiyalari, rasm yuklash va katalogni boshqarish.',
        },
        {
            'name': 'Integration',
            'description': '1C tizimi bilan sinxronizatsiya, background sync jarayonlari va progress status endpointlari.',
        },
        {
            'name': 'Agent Locations',
            'description': 'Mobil agentlar tomonidan yuborilgan geolokatsiya yozuvlari. Qurilma, lokatsiya, tarmoq, sensor va boshqa ma\'lumotlar bilan birga saqlanadi. Barcha maydonlar ixtiyoriy (faqat agent_code, latitude, longitude majburiy).',
        },
    ],
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'http',
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
            'description': 'JWT token. Format: Bearer <token>'
        }
    },
    'SERVERS': [
        {
            'url': 'http://localhost:8000',
            'description': 'Development server'
        },
        {
            'url': 'http://178.218.200.120:1596',
            'description': 'Production server',
        },
    ],
}

# JWT Settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS Settings
# Development uchun default origins
DEFAULT_CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
    "http://178.218.200.120:1596",
    "http://192.168.0.129",
    "http://192.168.0.129:8000",
    'http://178.218.200.120',
]
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
    if origin.strip()
] or DEFAULT_CORS_ALLOWED_ORIGINS

# Production uchun environment variable orqali
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Development uchun True, Production uchun False

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]