"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-h$&jhhj!%)h$ccokz4)0zsmxl069tm*-vb%37trdzb=0t3-grk')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

DEFAULT_ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '0.0.0.0',
    '178.218.200.120',
    '192.168.0.101',
    '192.168.0.110',
    '192.168.0.111',
    '192.168.0.129',
]
ALLOWED_HOSTS = [
    host.strip() for host in os.environ.get('ALLOWED_HOSTS', '').split(',')
    if host.strip()
] or DEFAULT_ALLOWED_HOSTS

DEFAULT_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://178.218.200.120:1596',
    'http://192.168.0.101',
    'http://192.168.0.110',
    'http://192.168.0.111',
    'http://192.168.0.129',
    'http://192.168.0.129:8000',
    'http://178.218.200.120:1596',
    'http://178.218.200.120'
]
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
] or DEFAULT_TRUSTED_ORIGINS


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'django_filters',
    'corsheaders',
    'ckeditor',
    'ckeditor_uploader',
    'imagekit',
    
    # Caching and background tasks
    # 'cacheops',  # Optional - uncomment if installed
    # 'django_q',  # Commented - incompatible with Django 5.2.7, using threading instead

    'client',
    'nomenklatura',
    'api',
    'integration',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 60,  # Increased timeout for sync operations
            'check_same_thread': False,  # Allow multiple threads
        },
        'CONN_MAX_AGE': 600,  # Connection pooling
    }
}

# SQLite WAL mode - improves concurrency and prevents "readonly database" errors
# This is set via database connection initialization
from django.db.backends.signals import connection_created
from django.dispatch import receiver

@receiver(connection_created)
def setup_sqlite_wal_mode(sender, connection, **kwargs):
    """Enable WAL mode for SQLite to improve concurrency"""
    if connection.vendor == 'sqlite':
        with connection.cursor() as cursor:
            cursor.execute("PRAGMA journal_mode=WAL;")
            cursor.execute("PRAGMA synchronous=NORMAL;")  # Faster than FULL, still safe
            cursor.execute("PRAGMA cache_size=-64000;")  # 64MB cache
            cursor.execute("PRAGMA temp_store=MEMORY;")  # Use memory for temp tables


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = []
STATIC_APP_DIR = BASE_DIR / 'static'
if STATIC_APP_DIR.exists():
    STATICFILES_DIRS.append(STATIC_APP_DIR)

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_MAX_AGE = 60 * 60 * 24 * 30  # 30 days

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


CKEDITOR_UPLOAD_PATH = 'uploads/ckeditor/'

# ============================================================================
# CACHING CONFIGURATION - High Performance for 10K+ requests/minute
# ============================================================================

# Redis cache backend - much faster than database cache
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            'IGNORE_EXCEPTIONS': True,  # Don't break if Redis is down
            # 'PARSER_CLASS': 'redis.connection.HiredisParser',  # Faster parser (optional, requires hiredis)
        },
        'KEY_PREFIX': 'ecatalog',
        'TIMEOUT': 300,  # 5 minutes default
        'VERSION': 1,
    }
}

# Cacheops - automatic ORM query caching (optional)
# Uncomment if django-cacheops is installed
# CACHEOPS_REDIS = {
#     'host': os.environ.get('REDIS_HOST', '127.0.0.1'),
#     'port': int(os.environ.get('REDIS_PORT', 6379)),
#     'db': int(os.environ.get('REDIS_DB', 2)),
#     'socket_timeout': 3,
#     'ignore_exceptions': True,
# }
# 
# CACHEOPS = {
#     # Cache all queries for 5 minutes
#     'api.*': {'ops': 'all', 'timeout': 300},
#     'client.*': {'ops': 'all', 'timeout': 300},
#     'nomenklatura.*': {'ops': 'all', 'timeout': 300},
#     'integration.*': {'ops': 'get', 'timeout': 600},
#     'api.imagestatus': {'ops': 'all', 'timeout': 3600},
#     'api.imagesource': {'ops': 'all', 'timeout': 3600},
#     'api.agentlocation': {'ops': 'get', 'timeout': 60},
# }

# Session backend - using database for reliability
# If Redis is unavailable, cache-based sessions fail
# Using database-backed sessions ensures sessions work even without Redis
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_CACHE_ALIAS = 'default'

# ============================================================================
# BACKGROUND TASKS - Using threading (django-q2 incompatible with Django 5.2)
# ============================================================================
# Background tasks are handled via threading.Thread in integration/views.py
# For production, consider using Celery or django-rq
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'PAGE_SIZE_QUERY_PARAM': 'page_size',
    'MAX_PAGE_SIZE': 100,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
    },
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'E-Catalog API',
    'DESCRIPTION': '''
# E-Catalog Microservice API Documentation

Bu API Project, Nomenklatura va Client ma'lumotlarini boshqarish uchun yaratilgan Django REST Framework asosidagi microservice.

## Asosiy Xususiyatlar

- **Project Management** — Project'lar va ularning rasmlarini boshqarish
- **Nomenklatura Management** — Nomenklatura'lar va ularning rasmlarini boshqarish
- **Client Management** — Client'lar va ularning rasmlarini boshqarish (Authentication talab qilinadi)
- **Agent Locations** — Mobil agentlar tomonidan yuborilgan geolokatsiya va qurilma ma'lumotlari
- **1C Integration** — 1C dan ma'lumotlarni yuklab olish
- **Image Processing** — Rasmlarni turli o'lchamlarda (sm, md, lg, thumbnail) saqlash
- **JWT Authentication** — Token-based authentication
- **Pagination** — Sahifalash bilan ma'lumotlarni olish
- **Search & Filtering** — Qidirish va filtrlash imkoniyatlari

## Authentication

1. `POST /api/token/` — `username` va `password` yuboring. Javobda `access` va `refresh` token olasiz.
2. `Authorization: Bearer <access_token>` header'ini barcha himoyalangan endpointlarda yuboring.
3. `POST /api/token/refresh/` — `refresh` token yuborib yangi `access` token oling.
4. `POST /api/token/verify/` — mavjud tokenning yaroqliligini tekshiring.

> Test uchun: `http POST http://localhost:8000/api/token/ username=admin password=secret`

## Projects

- `GET /api/v1/project/` — `search`, `code_1c`, `name`, `page`, `page_size` parametrlari mavjud.
- `POST /api/v1/project/` — yangi project yaratish (`code_1c`, `name`, `title`, `description`, `is_active`).
- `PUT/PATCH/DELETE /api/v1/project/{code_1c}/` — mavjud projectni yangilash yoki soft-delete qilish.
- Rasmlar:
  - `POST /api/v1/project-images/` — bitta rasm (`multipart/form-data`).
  - `POST /api/v1/project-images/bulk-upload/` — `project=<code>` va bir nechta `images[]`.

## Clients

- Barcha client endpointlari JWT authentication talab qiladi.
- `GET /api/v1/client/` — `search`, `client_code_1c`, `name`, `page`, `page_size`.
- `POST /api/v1/client/` va `PUT/PATCH/DELETE /api/v1/client/{client_code_1c}/`.
- Rasmlar:
  - `POST /api/v1/client-images/`
  - `POST /api/v1/client-images/bulk-upload/` — `client=<code>` va `images[]`.

## Nomenklatura

- `GET /api/v1/nomenklatura/` — `search`, `code_1c`, `name`, `page`, `page_size`.
- `POST /api/v1/nomenklatura/` va `PUT/PATCH/DELETE /api/v1/nomenklatura/{code_1c}/`.
- Rasmlar:
  - `POST /api/v1/nomenklatura-images/`
  - `POST /api/v1/nomenklatura-images/bulk-upload/` — `nomenklatura=<code>` va `images[]`.

## Agent Locations

- `GET /api/v1/agent-locations/` — Agent lokatsiya yozuvlari ro'yxati (JWT talab qilinadi).
  - Filterlar: `agent_code`, `region`, `platform`, `device_id`, `date_from`, `date_to`
- `POST /api/v1/agent-locations/` — Yangi lokatsiya yozuvini yaratish.
- `GET /api/v1/agent-locations/{id}/` — Bitta yozuvni olish.
- `PUT/PATCH /api/v1/agent-locations/{id}/` — Yozuvni yangilash.
- `DELETE /api/v1/agent-locations/{id}/` — Soft-delete qilish.

### AgentLocation maydonlari (barcha ixtiyoriy, faqat `agent_code`, `latitude`, `longitude` majburiy)

#### Agent ma'lumotlari
- `agent_code` *(string, required)* — Agent kodi
- `agent_name` *(string, optional)* — Agent ismi
- `agent_phone` *(string, optional)* — Agent telefoni
- `region` *(string, optional)* — Hudud yoki filial

#### Qurilma ma'lumotlari
- `device_id` *(string, optional)* — Qurilma ID (IMEI/UUID)
- `device_name` *(string, optional)* — Qurilma nomi
- `device_manufacturer` *(string, optional)* — Ishlab chiqaruvchi (Samsung, Apple, etc.)
- `device_model` *(string, optional)* — Qurilma modeli
- `platform` *(string, optional)* — OS (Android/iOS)
- `os_version` *(string, optional)* — OS versiyasi
- `screen_width`, `screen_height` *(integer, optional)* — Ekran o'lchamlari (px)
- `screen_density` *(decimal, optional)* — Ekran zichligi (DPI)
- `ram_total`, `ram_available` *(bigint, optional)* — RAM (byte)
- `storage_total`, `storage_available` *(bigint, optional)* — Xotira (byte)
- `camera_front`, `camera_back` *(boolean, optional)* — Kamera mavjudligi
- `camera_resolution` *(string, optional)* — Kamera o'lchami

#### Ilova ma'lumotlari
- `app_version` *(string, optional)* — Ilova versiyasi
- `app_build_number` *(string, optional)* — Build raqami
- `app_installation_date` *(datetime, optional)* — O'rnatilgan sana
- `app_last_update` *(datetime, optional)* — Oxirgi yangilanish

#### Lokatsiya ma'lumotlari
- `latitude` *(decimal, required)* — Latitude (WGS84)
- `longitude` *(decimal, required)* — Longitude (WGS84)
- `accuracy` *(decimal, optional)* — Aniqlik (metr)
- `altitude` *(decimal, optional)* — Balandlik (m)
- `speed` *(decimal, optional)* — Tezlik (m/s)
- `heading` *(decimal, optional)* — Yo'nalish (gradus)
- `city` *(string, optional)* — Shahar
- `country` *(string, optional)* — Davlat
- `postal_code` *(string, optional)* — Pochta indeksi
- `timezone` *(string, optional)* — Vaqt mintaqasi
- `location_provider` *(string, optional)* — Lokatsiya manbasi (GPS, Network, Passive)
- `address` *(string, optional)* — Geo reverse address

#### Batareya ma'lumotlari
- `battery_level` *(decimal, optional)* — Batareya foizi (%)
- `is_charging` *(boolean, optional)* — Zaryadlanayaptimi
- `battery_health` *(string, optional)* — Batareya holati (Good, Fair, Poor)
- `battery_temperature` *(decimal, optional)* — Batareya harorati (°C)
- `battery_voltage` *(decimal, optional)* — Batareya kuchlanishi (V)

#### Tarmoq ma'lumotlari
- `signal_strength` *(string, optional)* — Signal kuchi
- `network_type` *(string, optional)* — Tarmoq turi (WiFi, 4G, 5G, LTE)
- `wifi_ssid` *(string, optional)* — WiFi tarmoq nomi
- `wifi_bssid` *(string, optional)* — WiFi BSSID (MAC)
- `cellular_operator` *(string, optional)* — Mobil operator
- `cellular_network_type` *(string, optional)* — Mobil tarmoq turi (GSM, CDMA, LTE)
- `ip_address` *(IP, optional)* — IP manzil
- `connection_type` *(string, optional)* — Ulanish turi (WiFi, Mobile, Ethernet)

#### Sensor ma'lumotlari
- `accelerometer_x`, `accelerometer_y`, `accelerometer_z` *(decimal, optional)* — Accelerometer (m/s²)
- `gyroscope_x`, `gyroscope_y`, `gyroscope_z` *(decimal, optional)* — Gyroscope (rad/s)
- `magnetometer_x`, `magnetometer_y`, `magnetometer_z` *(decimal, optional)* — Magnetometer (μT)
- `proximity_sensor` *(decimal, optional)* — Proximity sensor (cm)
- `light_sensor` *(decimal, optional)* — Yorug'lik sensori (lux)

#### Atrof-muhit ma'lumotlari
- `temperature` *(decimal, optional)* — Harorat (°C)
- `humidity` *(decimal, optional)* — Namlik (%)
- `pressure` *(decimal, optional)* — Bosim (hPa)

#### Xavfsizlik ma'lumotlari
- `device_fingerprint` *(string, optional)* — Qurilma fingerprint (hash)
- `is_rooted` *(boolean, optional)* — Root qilinganmi
- `is_jailbroken` *(boolean, optional)* — Jailbreak qilinganmi (iOS)
- `encryption_enabled` *(boolean, optional)* — Shifrlash yoqilganmi
- `screen_lock_type` *(string, optional)* — Ekran qulfi turi (None, PIN, Pattern, Fingerprint, Face)

#### Qo'shimcha
- `logged_at` *(datetime, optional)* — Qurilmada yozilgan vaqt
- `note` *(text, optional)* — Izoh
- `metadata` *(JSON, optional)* — Qo'shimcha JSON ma'lumotlar

## Integration

- `GET /api/v1/integration/` — Integration sozlamalari ro'yxati (JWT talab qilinadi).
- `POST /api/v1/integration/{id}/sync-nomenklatura/` — 1C dan nomenklatura ma'lumotlarini fon rejimida yuklashni boshlaydi.
- `POST /api/v1/integration/{id}/sync-clients/` — 1C dan client ma'lumotlarini yuklaydi.
- `GET /api/v1/integration/sync-status/{task_id}/` — fon jarayonining progressini kuzatish.
- Sync javobidagi `task_id` orqali status endpointiga murojaat qiling (`status`: `fetching`, `processing`, `completed`, `error`).

### 1C Integration Sozlamalari

Integration sozlamasini yaratish uchun quyidagi maydonlar kerak (`IntegrationSerializer`):

| Field | Type | Description |
|-------|------|-------------|
| `name` | string | Integration nomi (unikal) |
| `project` | integer | Project ID (ForeignKey) |
| `wsdl_url` | string (URL) | 1C web-service WSDL manzili |
| `method_nomenklatura` | string | 1C dagi nomenklaturani qaytaruvchi method nomi |
| `method_clients` | string | 1C dagi clientlarni qaytaruvchi method nomi |
| `chunk_size` | integer | Bir qo‘ng‘iroqda qayta ishlanadigan elementlar soni |
| `description` | rich text | Integration haqida qo‘shimcha ma’lumot |

### 1C → E-Catalog ma'lumot mapping'i

#### Nomenklatura itemi (`sync-nomenklatura` uchun)

1C dan keladigan obyekt quyidagi atributlarni o‘z ichiga olishi kerak:

- `Code` *(string, required)* → `code_1c`
- `Name` *(string, required)* → `name`
- `Title` *(string, optional)* → `title`
- `Description` *(string/RichText, optional)* → `description`
- `Project` *(string, optional)* → Project nomi. Agar berilmasa, integration bilan biriktirilgan project ishlatiladi.
- `Images` *(list, optional)* → Rasm URL yoki fayl manzillari. Har bir elementda quyidagi kichik maydonlar bo‘lishi mumkin:
  - `Image` / `image` — original fayl URL
  - `ImageSm` / `image_sm` — kichik o‘lcham
  - `ImageMd` / `image_md` — o‘rta o‘lcham
  - `ImageLg` / `image_lg` — katta o‘lcham
  - `IsMain` / `is_main` — asosiy rasm flagi

#### Client itemi (`sync-clients` uchun)

- `Code` *(string, required)* → `client_code_1c`
- `Name` *(string, required)* → `name`
- `Email` *(string, optional)* → `email`
- `Phone` *(string, optional)* → `phone`
- `Description` *(string, optional)* → `description`
- `Images` *(list, optional)* → Project ga o‘xshash strukturadagi rasm ma’lumotlari

#### Integration log statuslari

- `fetching` — 1C dan ma’lumotlar olinmoqda
- `processing` — ma’lumotlar bazaga yozilmoqda
- `completed` — jarayon muvaffaqiyatli yakunlandi
- `error` — xatolik yuz berdi (`error_message` maydonida tafsilotlar qaytadi)

## Image Formats

- **image_url** — Original rasm
- **image_sm_url** — Kichik (300x300px) — mobil qurilmalar uchun
- **image_md_url** — O'rta (600x600px) — planshetlar uchun
- **image_lg_url** — Katta (1200x1200px) — desktop qurilmalar uchun
- **image_thumbnail_url** — Thumbnail (150x150px) — ro'yxatlar uchun

## Pagination

- `page` — Sahifa raqami (default: 1)
- `page_size` — Sahifadagi elementlar soni (default: 20, max: 100)

Response formati:
```json
{
  "count": 100,
  "next": "http://localhost:8000/api/v1/project/?page=2",
  "previous": null,
  "results": [...]
}
```

## Search & Filtering

- `search` — Barcha `search_fields` maydonlarida qidirish
- `field=value` — Aniq maydon bo'yicha filtrlash
- `ordering=field` — Tartiblash (`-field` — teskari tartib)

## Status Management

- `PATCH /api/v1/project/{code_1c}/` — `{"is_active": false}` yoki `{"is_deleted": true}`
- `PATCH /api/v1/client/{client_code_1c}/` — xuddi shunday
- `PATCH /api/v1/nomenklatura/{code_1c}/` — xuddi shunday

## Qo'shimcha Ma'lumotlar

- **Swagger UI**: http://localhost:8000/api/docs/
- **ReDoc**: http://localhost:8000/api/redoc/
- **OpenAPI Schema**: http://localhost:8000/api/schema/
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/v1/',
    'TAGS': [
        {
            'name': 'Authentication',
            'description': 'JWT token olish, yangilash va tekshirish endpointlari. Access tokenni `Authorization: Bearer` header ida yuboring.',
        },
        {
            'name': 'Projects',
            'description': 'Project CRUD operatsiyalari va rasm boshqaruvi (list, search, create, update, delete, bulk image upload).',
        },
        {
            'name': 'Clients',
            'description': 'Client CRUD operatsiyalari, faqat autentifikatsiya qilingan foydalanuvchilar uchun. Rasm boshqaruvi va bulk upload misollari.',
        },
        {
            'name': 'Nomenklatura',
            'description': 'Nomenklatura CRUD operatsiyalari, rasm yuklash va katalogni boshqarish.',
        },
        {
            'name': 'Integration',
            'description': '1C tizimi bilan sinxronizatsiya, background sync jarayonlari va progress status endpointlari.',
        },
        {
            'name': 'Agent Locations',
            'description': 'Mobil agentlar tomonidan yuborilgan geolokatsiya yozuvlari. Qurilma, lokatsiya, tarmoq, sensor va boshqa ma\'lumotlar bilan birga saqlanadi. Barcha maydonlar ixtiyoriy (faqat agent_code, latitude, longitude majburiy).',
        },
    ],
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'http',
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
            'description': 'JWT token. Format: Bearer <token>'
        }
    },
    'SERVERS': [
        {
            'url': 'http://localhost:8000',
            'description': 'Development server'
        },
        {
            'url': 'http://178.218.200.120:1596',
            'description': 'Production server',
        },
    ],
}

# JWT Settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS Settings
# Development uchun default origins
DEFAULT_CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
    "http://178.218.200.120:1596",
    "http://192.168.0.129",
    "http://192.168.0.129:8000",
    'http://178.218.200.120',
]
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
    if origin.strip()
] or DEFAULT_CORS_ALLOWED_ORIGINS

# Production uchun environment variable orqali
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Development uchun True, Production uchun False

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]