# Generated by Django 5.2.7 on 2026-01-19 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_userprofile_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1, help_text='Higher number = higher priority')),
                ('color', models.CharField(default='#000000', max_length=20)),
            ],
            options={
                'verbose_name': 'Visit Priority',
                'verbose_name_plural': 'Visit Priorities',
                'ordering': ['-level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VisitStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#000000', help_text='Hex color code', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_final', models.BooleanField(default=False, help_text='If true, visit is considered closed')),
            ],
            options={
                'verbose_name': 'Visit Status',
                'verbose_name_plural': 'Visit Statuses',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VisitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Visit Type',
                'verbose_name_plural': 'Visit Types',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VisitStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('input_type', models.CharField(choices=[('text', 'Text Input'), ('number', 'Number Input'), ('checkbox', 'Checkbox'), ('photo', 'Photo'), ('select', 'Selection')], default='checkbox', max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_steps', to='users.authproject')),
            ],
            options={
                'verbose_name': 'Visit Step',
                'verbose_name_plural': 'Visit Steps',
                'ordering': ['sort_order'],
            },
        ),
    ]
