# Generated by Django 5.2.7 on 2026-01-21 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitstep',
            name='visit_type',
            field=models.ForeignKey(blank=True, help_text='Specific visit type (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='references.visittype'),
        ),
    ]
