# Generated by Django 5.2.7 on 2026-01-30 08:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('USER', 'User'), ('ORGANIZATION', 'Organization'), ('PROJECT', 'Project')], default='USER', max_length=20)),
                ('entity_id', models.IntegerField(help_text='Linked Entity ID (e.g. User ID, Project ID)')),
                ('license_key', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('PENDING', 'Pending')], default='ACTIVE', max_length=20)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_unlimited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App License',
                'verbose_name_plural': 'App Licenses',
            },
        ),
        migrations.CreateModel(
            name='AppVersionMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.CharField(help_text='e.g. 1.0.4', max_length=20, unique=True)),
                ('is_mandatory_update', models.BooleanField(default=False)),
                ('min_supported_os', models.CharField(blank=True, max_length=50, null=True)),
                ('release_notes', models.TextField(blank=True, null=True)),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'App Version',
                'verbose_name_plural': 'App Versions',
            },
        ),
        migrations.CreateModel(
            name='AccessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('device_info', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='license.applicense')),
            ],
            options={
                'verbose_name': 'Access History',
                'verbose_name_plural': 'Access Histories',
            },
        ),
    ]
