# Generated by Django 5.2.7 on 2026-01-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesshistory',
            name='request_type',
            field=models.CharField(choices=[('ACTIVATION', 'Activation'), ('STATUS_CHECK', 'Status Check'), ('VERSION_ACTIVATION', 'Version Activation')], default='STATUS_CHECK', max_length=20),
        ),
        migrations.AddField(
            model_name='applicense',
            name='activation_count',
            field=models.IntegerField(default=0, help_text='Number of times activated'),
        ),
        migrations.AddField(
            model_name='applicense',
            name='device_id',
            field=models.CharField(blank=True, help_text='Unique device identifier', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicense',
            name='last_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
